Adds Docker Compose to ease local development - Resolves #85
ocodista/trampar-de-casa pull request #180
Opened 2023-11-12 03:10 UTC by jppradoleal

This pull request adds Supabase Docker Compose specs, and creates a base Compose spec that includes it and defines a service for `apps/web` with a volume mirroring it (to keep the hot reload feature).

It also defines a Makefile to ease the process of creating the .env files and running the migrations, I've splitted the db:migrate as `generate-types` seemed unnecessary.

---

I've used the email-sender Dockerfile as base, which already follows the best conventions, but the image size is kind of a pain, with almost 4gb, the main cause is the dependencies. `yarn install` layer is the biggest one, I dont think we can optimize it without pruning some dependencies.

![image](https://github.com/ocodista/trampar-de-casa/assets/23669434/38ec1414-ace9-4d88-bbc5-0fc8aadd61f9)

Considering that the image must be rebuilt only when the dependencies changes, it's not a problem as big as it seems.

2023-11-12 13:23 UTC, albertofp commented
Let's fucking goooo
Tiny nit: maybe add more to the .dockerignore to reduce image size a bit more (dockerfile, logs, readmes etc)
Not sure how the --prune flag works but maybe .dockerignore-ing **/node-modules helps?

2023-11-12 19:16 UTC, jppradoleal commented
The .dockerignore is actually a symbolic link to the .gitignore, I am not sure if Docker is able to parse it as it should. I will try to hardcode some values in it, and see if the size changes.

2023-11-12 23:17 UTC, jppradoleal commented
Yeah, `.dockerignore` as a symbolic link to `.gitignore` is parsed as it should. Hardcoding the values from one into another didn't change the image size.

2023-11-13 01:11 UTC, ocodista requested changes

2023-11-13 01:11 UTC, ocodista commented on docker/.env.example
It seems to me that this entire `docker` folder is actually a `supabase` image folder.

What do you think about renaming?

2023-11-13 01:11 UTC, ocodista commented on apps/web/.dockerignore
Does this works?

We need to make sure that no .git, folder is being pushed to the docker image.

2023-11-13 02:13 UTC, jppradoleal commented on apps/web/.dockerignore
![image](https://github.com/ocodista/trampar-de-casa/assets/23669434/1bdcbcff-d8f2-400e-bc7b-05d3150c8b82)

Yeah, it does work :)

2023-11-13 02:17 UTC, jppradoleal commented on docker/.env.example
Done 👍

2023-11-13 02:21 UTC, jppradoleal commented
I've renamed the docker folder to supabase, and did some cleaning on its folders.

2023-12-08 14:08 UTC, closed without merging