feat: Added Global loader
ocodista/trampar-de-casa pull request #20
Opened 2023-06-23 20:10 UTC by raphaelvdossantos

Adding global loader.

Global Context to control loading.
Global function to add loading to a function.

Disclaimer: VScode preferences polluted part of the PR.
File Hero.tsx:
- Changes on lines 10, 20 and 245

2023-06-23 20:56 UTC, ocodista commented
Are you using prettier?

Please run a `yarn eslint ./apps --fix` before commiting.

A few files are wrongly formatted.

2023-06-23 22:35 UTC, ocodista requested changes
Infelizmente não está funcionando, você pode acessar o link do preview da Vercel nos comentários

2023-06-24 14:03 UTC, JoaoVictor6 commented
> Infelizmente não está funcionando, você pode acessar o link do preview da Vercel nos comentários

Parece que o contexto deste hook nao existe na pagina. Estranho, ja que o Provider do mesmo eh passado no `Layout.tsx` e localmente funciona(pelo menos aqui)

2023-06-24 14:06 UTC, JoaoVictor6 commented on apps/web/app/context/Loading.tsx
> +  const withLoading = async (f: () => Promise<unknown>) => {
Bem legal essa HOF para as promises usarem o loading. Eu iria expor os estados porem dessa forma parece ser bem melhor, menos trabalhoso pra quem usar o contexto.

2023-06-24 15:06 UTC, raphaelvdossantos commented
> > Infelizmente não está funcionando, você pode acessar o link do preview da Vercel nos comentários
> 
> Parece que o contexto deste hook nao existe na pagina. Estranho, ja que o Provider do mesmo eh passado no `Layout.tsx` e localmente funciona(pelo menos aqui)

Sim, inclusive é o que me deixa na dúvida se esse é o build do segundo commit porque no primeiro eu realmente tinha enviado sem o Provider - tinha feito um PR antes mas prettier zoou com toda a formatação então abri esse daqui tentando salvar aquele outro.

2023-06-24 16:15 UTC, ocodista commented
> > > Infelizmente não está funcionando, você pode acessar o link do preview da Vercel nos comentários
> > 
> > 
> > Parece que o contexto deste hook nao existe na pagina. Estranho, ja que o Provider do mesmo eh passado no `Layout.tsx` e localmente funciona(pelo menos aqui)
> 
> Sim, inclusive é o que me deixa na dúvida se esse é o build do segundo commit porque no primeiro eu realmente tinha enviado sem o Provider - tinha feito um PR antes mas prettier zoou com toda a formatação então abri esse daqui tentando salvar aquele outro.

O GitHub está acusando conflito em alguns arquivos, então não consigo pedir para a vercel gerar um novo preview, você consegue corrigir?

Aí gero um novo para ver se funciona, se funcionar, já aprovo e dou o merge.

2023-06-24 19:57 UTC, raphaelvdossantos commented
> O GitHub está acusando conflito em alguns arquivos, então não consigo pedir para a vercel gerar um novo preview, você consegue corrigir?
> 
> Aí gero um novo para ver se funciona, se funcionar, já aprovo e dou o merge.

Resolvidos os conflitos, novo push feito.

2023-06-24 20:07 UTC, raphaelvdossantos commented on apps/web/app/context/Loading.tsx
> +  const withLoading = async (f: () => Promise<unknown>) => {
Valeu, fiquei com medo de ser muito canhão pra matar formiga
Acho que simplifica um bocado pra implementar a funcionalidade onde quiser.

2023-06-25 00:18 UTC, ocodista commented on apps/web/app/layout.tsx
> +export default function RootLayout({ children }) {
```suggestion
export default function RootLayout ({ children }) {
```

2023-06-25 00:19 UTC, ocodista commented
@raphaelvdossantos só para constar, seu lint ainda tá zoado, mas arrumei aqui para esse caso.

![image](https://github.com/ocodista/trampar-de-casa/assets/19851187/9c7a8b39-b973-4490-8743-9367938d97bd)

2023-06-25 00:25 UTC, ocodista approved these changes
Funcionou, obrigado!

2023-06-25 00:26 UTC, merged