Testimonial page
ocodista/trampar-de-casa pull request #205
Opened 2023-12-08 20:55 UTC by JoaoVictor6

## Testimonial Page
Based on #197, I created a testimonial page

The idea is to create a local where subscribers can tell us about how they got a job with trampar de casa

![Page Preview](https://github.com/ocodista/trampar-de-casa/assets/68869379/766789f4-bebf-4acb-9a09-d19bfbf18089)

Now if you want to access this page, click on "Consegui um emprego" on the header of the weekly email😁

![image](https://github.com/ocodista/trampar-de-casa/assets/68869379/6ba22112-978f-4285-b54e-fc2d7380fd41)

2023-12-11 13:21 UTC, JoaoVictor6 commented
I Added a error message on the skill field 
![image](https://github.com/ocodista/trampar-de-casa/assets/68869379/21379993-34c0-4233-b6e7-fa7b5d4947d0)

2023-12-12 18:10 UTC, ocodista requested changes

2023-12-12 18:10 UTC, ocodista commented on apps/web/app/subscribers/testemunho/[id]/saveTestimonial.ts
> +    text: `User with email ${email} sent a testimonial!`,
```suggestion
  resend.emails.send({
    from: 'logger@trampardecasa.com.br',
    subject: '[Trampar de Casa] New hire!',
    to: ownerEmail,
    text: `User ${email} got a new job!`,
```

2023-12-12 18:10 UTC, ocodista approved these changes

2023-12-12 18:12 UTC, merged