feat: adiciona a possibilidade de rodar via docker
ocodista/trampar-de-casa pull request #24
Opened 2023-06-25 00:32 UTC by byancar

2023-06-25 01:00 UTC, anti-duhring requested changes

2023-06-25 01:00 UTC, anti-duhring commented on Dockerfile
Can you add a [supabase local setup](https://supabase.com/docs/guides/getting-started/local-development) also? We already have this [`db-start`](https://github.com/ocodista/trampar-de-casa/blob/main/apps/web/package.json#L10C18-L10C36) script to start a local development server

2023-06-25 01:15 UTC, anti-duhring commented on Dockerfile
We also need a [`npx prisma migrate && npx prisma generate command`](https://www.prisma.io/docs/guides/deployment/deploy-database-changes-with-prisma-migrate) to setup prisma client

2023-06-25 13:35 UTC, byancar commented on Dockerfile
Good morning! 

You guys will need whole supabase studio? I just put supabase/postgres, but I can add more feat if as need 😄.

2023-06-25 23:37 UTC, ocodista requested changes

2023-06-25 23:37 UTC, ocodista commented on docker-compose.yml
I have one question:

Now that we have the supabase postgres container, shouldn't we pass the envs related to supabase to the `trampar-conteiner`?

Otherwise I think it won't work.

2023-06-27 19:50 UTC, ocodista commented on docker-compose.yml
@byancar

2023-06-27 21:14 UTC, byancar commented on docker-compose.yml
Sorry for delay in replying 😅 I put .env.example to .env inside of container. Is that enough? 🤔

2023-07-03 16:27 UTC, ocodista commented
@byancar do you still plan to work on this one?

It's missing the `environment` section with all the properties from the file `apps/web/.env.example` pointing to the `supabase` instance of the docker-compose.yml

2023-07-03 16:48 UTC, byancar commented on docker-compose.yml
Hi ocodista!

I don't know if it's what you guys expect but I uploaded a fix in the last PR :D

2023-07-10 22:36 UTC, ocodista commented
@byancar I just tested this branch and unfortunately it's not complete.

The happy path would be:

- docker-compose up
- Go to localhost:3000
- Add your email
- Click on the CTA
- Confetti is shown (meaning that it added to the db)

But when I try to click the CTA, the server throws an error that the supabase key is missing.

![image](https://github.com/ocodista/trampar-de-casa/assets/19851187/d5c8af13-58c3-4a10-b272-9134b5aa4604)


I would love to have the docker configured for the dev env of this project, but I don't have the time right now to fix it

2023-07-13 14:04 UTC, closed without merging