Add global error handler
ocodista/trampar-de-casa pull request #29
Opened 2023-06-25 19:02 UTC by JoaoVictor6

I create a simple error boundary for capturing exceptions and display a generic toast as mentioned in issue #26

Above a demo video:

https://github.com/ocodista/trampar-de-casa/assets/68869379/e9417dd2-f0ba-41a7-aa8d-ab5b5b628974

### Some questions
- The message is good?
- Make sense to create a generic fallback UI?

2023-06-25 19:04 UTC, JoaoVictor6 commented on apps/web/prisma/client/index.js
> +      "value": "/home/joao/FOSS/trampar-de-casa/apps/web/prisma/client",
This file is necessary?

2023-06-25 23:32 UTC, ocodista requested changes

2023-06-25 23:32 UTC, ocodista commented on apps/web/global/GlobalErrorBoundary.tsx
> +}
Is there a way to do this with react hooks?

Also, as we're using next, maybe we could use the suggested error handler https://nextjs.org/docs/app/building-your-application/routing/error-handling

You could try this by throwing an error on the click of the button of the Hero section

2023-06-26 23:49 UTC, JoaoVictor6 commented
# Some chances

https://github.com/ocodista/trampar-de-casa/assets/68869379/66e86038-ce4a-44b4-bb00-b20aa7f201c9

- Using nextjs error handling approach
- Add a shadcn button for fallback UI

Valid @ocodista ? maybe fallback UI is not necessary

2023-06-27 19:50 UTC, ocodista commented
João, peço desculpas mas acabei implementando o component global-error.tsx na pasta root que já faz esse papel.

Se quiser, você pode tentar pegar essa estilização de botão (ou página) e colocar nele, aí eu aprovo o PR, o que vc acha?

2023-06-28 00:44 UTC, JoaoVictor6 commented
> João, peço desculpas mas acabei implementando o component global-error.tsx na pasta root que já faz esse papel.
> 
> Se quiser, você pode tentar pegar essa estilização de botão (ou página) e colocar nele, aí eu aprovo o PR, o que vc acha?

Opa, tudo bem :)

2023-06-28 15:26 UTC, ocodista commented
Closing for now.

If you're able to enhance the global-error page, please open a new PR.

Thank you!

2023-06-28 15:26 UTC, closed without merging