feat: config react-query / subs fetch
ocodista/trampar-de-casa pull request #51
Opened 2023-06-29 03:27 UTC by Lucas-Onofre

2023-06-29 13:32 UTC, anti-duhring commented
Nice! Can you solve the conflicts within `yarn.lock`?

2023-06-29 14:42 UTC, ocodista approved these changes
Outstanding!

Thank you!!!

2023-06-29 15:19 UTC, ocodista requested changes

2023-06-29 15:19 UTC, ocodista commented on package.json
>    }
This dependency is at the wrong package.json file.

You should add it on the `apps/web` page

2023-07-04 21:59 UTC, ocodista commented
Close as I think it's already merged.

2023-07-04 21:59 UTC, closed without merging