Sergiohdljr feat/front/add react query onsub calls
ocodista/trampar-de-casa pull request #55
Opened 2023-06-29 23:07 UTC by anti-duhring

2023-06-29 23:25 UTC, ocodista requested changes
@anti-duhring was there any merge errors when merging the previous PR with this one?

2023-06-29 23:25 UTC, ocodista commented on apps/web/app/landing-page/Hero.tsx
> +  const { data:subscribersCount } = useQuery<number>( 'subscribres', async () => await getSubscribersCount())
The lint seems broken, there shouldn't be a space before 'subscribers'.

It has also a typo.

@anti-duhring haven't you merged the previous PR into this one?

I kinda preferred the other name. (with count)

2023-06-29 23:25 UTC, ocodista commented on apps/web/app/landing-page/Hero.tsx
> +  const { data:subscribersCount } = useQuery<number>( 'subscribres', async () => await getSubscribersCount())
```suggestion
  const { data: subscribersCount } = useQuery<number>('subscribersCountQuery', async () => await getSubscribersCount())
```

2023-06-30 12:47 UTC, anti-duhring commented
> @anti-duhring was there any merge errors when merging the previous PR with this one?

I couldn't resolve the `yarn.lock` conflict in that branch, so I cloned that PR into this branch

2023-06-30 14:03 UTC, ocodista requested changes

2023-06-30 14:03 UTC, ocodista commented on apps/web/app/landing-page/Hero.tsx
> +  }
Please add type and return something.

```suggestion
  const getSubscribersCount = async (): Promise<number | null> => {
    const response = await fetch(ApiRoutes.Subscribers)
    if (!response?.ok) return null
    const count = await response.json()
    return count
  }
```

2023-07-01 01:31 UTC, ocodista approved these changes

2023-07-02 23:21 UTC, merged