refactor:landing-page
ocodista/trampar-de-casa pull request #81
Opened 2023-07-06 04:13 UTC by gahcalistro

# Refactor: visual adjustments and removed unnecessary imports/elements/components

## Refactor Landing page
**Just for reference: images on the left are the original and on the
right are with modifications*

1. resized goToTop button and designed an smooth animation
<img src="https://i.imgur.com/vyMx7g5.gif" alt="go to top button" width="200px"/>

2. changed confetti element to other animation using canvas with fade-out effect
now, useEffect and useState is not needed anymore in this case
<img src="https://i.imgur.com/YsKDjDz.gif" alt="confetti animation" height="300px"/>

4. changed icons and highlighted words to make the clickable card intuitive
<img src="https://i.imgur.com/7DbRWmU.png" alt="cards" width="500px"/>

*[Icons](https://www.svgrepo.com/collection/scarlab-solid-oval-interface-icons/) are from svgRepo and are free to use. 

5. `Hero.tsx` was duplicated 
<img src="https://i.imgur.com/sVqfoZu.png"  alt="cards" width="200px"/>

6. reorganized files to better understand its purposes
<img src="https://i.imgur.com/6w7CKf9.png"  alt="cards" width="300px"/>

7. `loadingContext`
Exported a function calling useContext to avoid import both useContext and LoadingContext unnecessarily. This will allow to import just the data from the context. 
Usage: 
```
import { useLoadingContext } from "contexts/LoadingContext"

const { isLoading } = useLoadingContext()
```

8. removed imports that were not being used

2023-07-06 20:07 UTC, ocodista commented
@gahcalistro Thank you for your contributions!

2023-07-06 20:10 UTC, ocodista requested changes
Other than the confetti agressiveness, I'll approve the other ones.

Thank you!

2023-07-06 20:10 UTC, ocodista commented on apps/web/app/utils/confetti.ts
> +}
Hey, I liked the structural changes but I think that poping them from random places on the screen it's too agressive.

Could you please refactor this one to drop "fireworks" from the top?

2023-07-06 22:23 UTC, gahcalistro commented
I've made other changes

1. horizontally centralized and responsively resized images
<img src="https://i.imgur.com/E3H2rjk.png" width="600px" />

2. remanaged space in cards

<img src="https://i.imgur.com/kC8x8gH.png" width="300px" />

3. reduced size between section description and card.
also increased line heigth to be better to read
<img src="https://i.imgur.com/R9KiPk0.png" width="500px" />

4. I know that is just a slight detail but I aligned theses dotted lines
<img src="https://i.imgur.com/ITARWM3.png" width="600px" />

5. I fixed section titles
Smartphones like Galaxy Fold would be affected with this bug.
<img src="https://i.imgur.com/4oATAiP.png" width="300px" />
I'm trying to fix this bug in `HowItWorks" numbered list as well

2023-07-07 00:33 UTC, ocodista commented on apps/web/app/utils/confetti.ts
> +  const duration = 8000 // 8 seconds
```suggestion
  const duration = 6_500
```

2023-07-07 00:34 UTC, ocodista commented on apps/web/app/utils/confetti.ts
> +}
I made a commit to update the duration from 8s to 6.5s, other than that it looks great.

Thank you!

2023-07-07 00:52 UTC, gahcalistro commented
I was checking lighthouse to see any changes in best practices and there is an error in console.log about "plausible.io". Do you know what is this about? I don't know how to fix it.
<img src="https://i.imgur.com/oSBHWM5.png" width="400px" />

2023-07-07 01:11 UTC, ocodista commented
> I was checking lighthouse to see any changes in best practices and there is an error in console.log about "plausible.io". Do you know what is this about? I don't know how to fix it. <img alt="" width="400px" src="https://camo.githubusercontent.com/b9d835d82e20731f8391dd47da7cd5026dc2c8826f83d274b793b903b0b362a7/68747470733a2f2f692e696d6775722e636f6d2f6f534248574d352e706e67">

I think there's no problem as it doesn't happen on the production.

It is the analytics tool we use, but as you're not running from the domain, it may throw some errors

2023-07-07 01:11 UTC, ocodista approved these changes

2023-07-07 01:11 UTC, merged